//@BASE_URL = {{BASE_URL}}
@BASE_URL = http://support.i2gether.com/api
### Run status check
GET {{BASE_URL}}/tickets

### Create a ticket
POST {{BASE_URL}}/tickets
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbeyJwcm9qZWN0SWQiOjEsInJvbGUiOiJDdXN0b21lciJ9XSwiaWF0IjoxNzE2NzAwNDU5LCJleHAiOjE3MTY3MDQwNTl9.LEVY0L9XblmE9AVpFEIRWVvOC8cuicpnkg9TvF43eK0"
{
  "topicId": 1,
  "title": "Ticket Title",
  "description": "Ticket Description",
  "priority": "P1",
  "requestedBy": "John Doe",
  "attachments": ["file1.pdf", "file2.png"],
  "fyiTo": ["Manager1", "Manager2"]
}

### Update a ticket
PUT {{BASE_URL}}/tickets/1
Content-Type: application/json

{
  "title": "Updated Ticket Title",
  "description": "Updated Ticket Description",
  "priority": "P2",
  "requestedBy": "Jane Smith",
  "attachments": ["file3.doc"],
  "fyiTo": ["Manager3"]
}

### Delete a ticket
DELETE {{BASE_URL}}/tickets/6


### Create Organization (POST /api/organizations)
POST {{BASE_URL}}/organizations
Content-Type: application/json

{
  "code": "TIL",
  "name": "Together Initiatives (p) Limited",
  "address": "147/E Green Road, Dhaka"
}

### Get All Organizations (GET /api/organizations)
GET {{BASE_URL}}/organizations

### Get Organization by ID (GET /api/organizations/:id)
GET {{BASE_URL}}/organizations/1

### Update Organization (PUT /api/organizations/:id)
PUT {{BASE_URL}}/organizations/1
Content-Type: application/json

{
  "code": "org1",
  "name": "Updated Organization",
  "address": "456 Elm St"
}

### Delete Organization (DELETE /api/organizations/:id)
DELETE {{BASE_URL}}/organizations/1

### Create Project (POST /api/projects)
POST {{BASE_URL}}/projects
Content-Type: application/json

{
  "organizationId": 1,
  "code": "LIC",
  "name": "LIC Application",
  "description": "LIC Application"
}


### Get All Projects (GET /api/projects)
GET {{BASE_URL}}/projects

### Get project by id
GET {{BASE_URL}}/projects

### Update Project (PUT /api/projects/:id)
PUT {{BASE_URL}}/projects/1
Content-Type: application/json

{
  "code": "proj1",
  "name": "Updated Project",
  "description": "Updated project description"
}

### Delete a project
DELETE {{BASE_URL}}/projects/1

### Create Topic (POST /api/topics)
POST {{BASE_URL}}/topics
Content-Type: application/json

{
  "projectId": 1,
  "name": "Topic 1",
  "description": "Description of Topic 1"
}

### Get All Topics (GET /api/topics)
GET {{BASE_URL}}/topics

### Get Topic by ID (GET /api/topics/:id)
GET {{BASE_URL}}/topics/1

### Update Topic (PUT /api/topics/:id)
PUT {{BASE_URL}}/topics/1
Content-Type: application/json

{
  "name": "Updated Topic 1",
  "description": "Updated description of Topic 1"
}

### Delete Topic (DELETE /api/topics/:id)
DELETE {{BASE_URL}}/topics/1

### User Registration
POST {{BASE_URL}}/register
Content-Type: application/json

{
  "name": "John Doe 1",
  "email": "john1@example.com",
  "phoneNumber": "1234567890",
  "password": "password123"
}

### User Login
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "john1@example.com",
  "password": "password123"
}

### Change Password
PUT {{BASE_URL}}/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGVzIjpbXSwiaWF0IjoxNzE0NjMxOTcyLCJleHAiOjE3MTQ2MzU1NzJ9.qVYtfq6kIt0HQP1Ii8OWxgyZNkijGdataUtpSzvTckw
Content-Type: application/json

{
  "userId": 1,
  "currentPassword": "password123",
  "newPassword": "newpassword456"
}

### Assign Role to User for a Project
POST {{BASE_URL}}/user-roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGVzIjpbXSwiaWF0IjoxNzE0NjQ5NzE3LCJleHAiOjE3MTQ2NTMzMTd9.IXUfuo0csbSXSia4yJzpFRGIxqh_ZkCXUK7_pnLIGec
Content-Type: application/json

{
  "userId": 3,
  "projectId": 1,
  "role": "Customer"
}

### Update User Role for a Project
PUT {{BASE_URL}}/user-roles/:id
Authorization: Bearer <JWT token>
Content-Type: application/json

{
  "role": "Support"
}

### Delete User Role for a Project
DELETE {{BASE_URL}}/user-roles/:id
Authorization: Bearer <JWT token>
