#@BASE_URL = http://support.i2gether.com/api
@BASE_URL = http://localhost:3000/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGVzIjpbeyJwcm9qZWN0SWQiOjEsInJvbGUiOiJDdXN0b21lciJ9XSwiaWF0IjoxNzE2NDY4NTU2LCJleHAiOjE3MTY0NzIxNTZ9.2aZWZ8yeH0XSqmYzrhff_MjCK-TEms2Da7LqU-4Iw_8

### User Login
# @name postLogin
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "john1@example.com",
  "password": "password123"
}
### Get Token
@TOKEN = {{postLogin.response.body.token}}


### Create Project (POST /api/projects)
POST {{BASE_URL}}/projects
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "organizationId": 1,
  "code": "LIC",
  "name": "LIC Application",
  "description": "LIC Application"
}


### Get All Projects (GET /api/projects)
GET {{BASE_URL}}/projects
Authorization: Bearer {{TOKEN}}

### Get project by id
GET {{BASE_URL}}/projects
Authorization: Bearer {{TOKEN}}
### Update Project (PUT /api/projects/:id)
PUT {{BASE_URL}}/projects/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "code": "proj1",
  "name": "Updated Project",
  "description": "Updated project description"
}

### Delete a project
DELETE {{BASE_URL}}/projects/1
Authorization: Bearer {{TOKEN}}
