@BASE_URL = http://support.i2gether.com/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGVzIjpbeyJwcm9qZWN0SWQiOjEsInJvbGUiOiJDdXN0b21lciJ9XSwiaWF0IjoxNzE2NDY4NTU2LCJleHAiOjE3MTY0NzIxNTZ9.2aZWZ8yeH0XSqmYzrhff_MjCK-TEms2Da7LqU-4Iw_8

### User Login
# @name postLogin
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "sharifruet@gmail.com",
  "password": "pass@123"
}
### Get Token
@TOKEN = {{postLogin.response.body.token}}


### Create a new ticket
POST {{BASE_URL}}/tickets
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "topicId": 2,
  "title": "New Ticket",
  "description": "Description of the new ticket",
  "priority": "P3",
  "requestedBy": "John Doe",
  "attachments": ["attachment1.jpg", "attachment2.pdf"],
  "fyiTo": ["user1@example.com", "user2@example.com"]
}

### Update an existing ticket
PUT {{BASE_URL}}/tickets/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "Updated Ticket",
  "description": "Updated description"
}

### Delete a ticket by ID
DELETE {{BASE_URL}}/tickets/1
Authorization: Bearer {{TOKEN}}

### Get all tickets
GET {{BASE_URL}}/tickets
Authorization: Bearer {{TOKEN}}

### Get a ticket by ID
GET {{BASE_URL}}/tickets/1
Authorization: Bearer {{TOKEN}}

### Get tickets by project
GET {{BASE_URL}}/tickets/project/1
Authorization: Bearer {{TOKEN}}